In [ ]:
import this

In [1]:
x = [1, 3, 5, 7, 8, 9, 10]

# The following is OK, because "x" is a list, and hence mutable
x[3] = 17     
print(x)  

[1, 3, 5, 17, 8, 9, 10]


In [ ]:
#| eval: false

# The following will return an error, because x_tuple is a tuple, and hence 
# immutable.
x_tuple = (1, 3, 5, 6, 8, 9, 10)
x_tuple[3] = 17 

In [ ]:
x_list = [1, 2, 3]
x_tuple = (1, 2, 3)
x_dict = {'a': 1, 'b': 2, 'c': 3} # access with x_dict['a']

In [ ]:
char_list = ['P', 'y', 't', 'h', 'o', 'n']
char_list[0]           # returns first element
char_list[-1]          # returns last element
len(char_list)         # returns number of elements in list-like object.
char_list[::2]         # from first to last, every 2 apart.

In [2]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
matrix1 = np.array([array1, array2])
print(matrix1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
matrix1[0, 0::3]       # returns first row, columns 1 and 4
matrix1[1, 1:3]        # returns second row, columns 2 and 3

array([7, 8])

In [4]:
# To obtain the dimensions of an array:
matrix1.shape
# To transpose a 2-D array
matrix1.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
np.vstack([matrix1, array1])

np.hstack([array1.reshape((5,1)), 
           array2.reshape((5,1)),
           matrix1.T])

In [5]:
import pandas as pd

data = {'X': [1,2,3,4,5,6], 'Y': [6,5,4,3,2,1]}
df = pd.DataFrame(data, columns =['X', 'Y'])
print(df)

   X  Y
0  1  6
1  2  5
2  3  4
3  4  3
4  5  2
5  6  1


In [6]:
col_x = df.X
col_x[0:3]

0    1
1    2
2    3
Name: X, dtype: int64

In [7]:
data1 = pd.read_table('data/crab.txt', header=0, sep="\\s+")
data1.head()

color  spine  width  satell   weight
0      3      3   28.3       8  9999.00
1      4      3   22.5       0     1.55
2      2      1   26.0       9     2.30
3      4      3   24.8       0     2.10
4      4      3   26.0       4     2.60

In [8]:
varnames = ["Subject", "Gender", "CA1", "CA2", "HW"]
data2 = pd.read_table('data/ex_1.txt', header=None, 
                      names=varnames, sep="\\s+")
data2

Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C

In [16]:
# retrieve rows 0,1,2 and columns from color to width
data1.loc[0:2, 'color':'width']

# retrieve every second row starting from row 0 until row 5, and all columns
data1.loc[0:5:2, ]

color  spine  width  satell  weight
0      3      3   28.3       8  9999.0
2      2      1   26.0       9     2.3
4      4      3   26.0       4     2.6

In [17]:
data1.iloc[0:2, 0:2]

color  spine
0      3      3
1      4      3

In [18]:
data2[data2.Gender == "M"]

data2[(data2.Gender == "M") & (data2.CA2 > 85)]

Subject Gender  CA1  CA2 HW
1        7      M   85   89  A

In [19]:
for i in x[:2]:
  print(f"The current element is {i}.")

The current element is 1.
The current element is 3.


In [20]:
dict1 = {'holmes': 'male', 'watson': 'male', 'mycroft': 'male', 
         'hudson': 'female', 'moriarty': 'male', 'adler': 'female'}
# dict1['hudson']

for x in dict1.keys():
    print(f"The gender of {x} is {dict1[x]}")

The gender of holmes is male
The gender of watson is male
The gender of mycroft is male
The gender of hudson is female
The gender of moriarty is male
The gender of adler is female


In [21]:
x = 0          
test = True 

while test:
    x += 1  
    test = x < 6
    print(f"{x**2}, {test}")

1, True
4, True
9, True
16, True
25, True
36, False


In [22]:
for y in np.arange(6):
    print(f"The square of {y} is {y**2}.")

The square of 0 is 0.
The square of 1 is 1.
The square of 2 is 4.
The square of 3 is 9.
The square of 4 is 16.
The square of 5 is 25.


In [ ]:
#| eval: false
def fn_name(arguments):
  Python statements
  ...
  Returned object

In [23]:
import math

def circumference(radius):
    return 2 * math.pi * radius 

circumference(1.3)

8.168140899333462

In [ ]:
#| eval: false
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: '